# Generated by Django 3.2.4 on 2021-06-05 22:35

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14),
        ),
    ]
