# Generated by Django 3.2.4 on 2021-06-05 23:37

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_cliente', '0002_alter_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11),
        ),
    ]
